# Generated by Django 5.2.10 on 2026-01-31 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='share_enabled',
        ),
    ]
