# Generated by Django 5.2.10 on 2026-01-10 15:16
import os
from django.db import migrations

def create_admin(apps, schema_editor):
    User = apps.get_model('users', 'User')

    password = os.environ.get('ADMIN_PASSWORD')
    if not password:
        raise RuntimeError('ADMIN_PASSWORD is not set (check .env)')

    if User.objects.filter(username='admin').exists():
        return

    User.objects.create_superuser(
        username='admin',
        password=password,
        email='admin@email.god',
        full_name='Administrator',
        is_admin=True,
    )

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_admin),
    ]
