# Generated by Django 5.2.10 on 2026-02-10 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_storage_rel_path_check'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='users_user_storage_rel_path_not_empty',
        ),
    ]
